const peliculas = [
  {
    id: 1,
    titulo: "The Shawshank Redemption",
    generos: "Drama",
    anio: 1994,
    director: "Frank Darabont",
    likes: 1850,
    portada: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
  },
  {
    id: 2,
    titulo: "The Godfather",
    generos: "Crime ,Drama",
    anio: 1972,
    director: "Francis Ford Coppola",
    likes: 2100,
    portada:
      "https://www.tallengestore.com/cdn/shop/products/Movie_Poster_-_Marlon_Brando_-_The_Godfather_-_Tallenge_Hollywood_Poster_Collection_5e28565f-0a5c-4af0-83e3-b5247a2d12db.jpg?v=1591603231",
  },
  {
    id: 3,
    titulo: "The Dark Knight",
    generos: "Action ,Crime, Drama",
    anio: 2008,
    director: "Christopher Nolan",
    likes: 2800,
    portada:
      "https://play-lh.googleusercontent.com/auIs5tjWlLYaFPGClZOJ7m5YVbnX6uBvz0X02r8TkwFKdzE53ww2MqWSS9gU0YNqoYwvpg=w480-h960-rw",
  },
  {
    id: 4,
    titulo: "Pulp Fiction",
    generos: "Crime, Drama",
    anio: 1994,
    director: "Quentin Tarantino",
    likes: 1700,
    portada: "https://static.posters.cz/image/750webp/1288.webp",
  },
  {
    id: 5,
    titulo: "Inception",
    generos: "Action , Adventure, Sci-Fi",
    anio: 2010,
    director: "Christopher Nolan",
    likes: 2600,
    portada: "https://storage.googleapis.com/pod_public/800webp/263129.webp",
  },
  {
    id: 6,
    titulo: "Fight Club",
    generos: "Drama",
    anio: 1999,
    director: "David Fincher",
    likes: 1900,
    portada: "https://storage.googleapis.com/pod_public/800webp/180854.webp",
  },
  {
    id: 7,
    titulo: "Forrest Gump",
    generos: "Drama, Romance",
    anio: 1994,
    director: "Robert Zemeckis",
    likes: 2400,
    portada: "https://storage.googleapis.com/pod_public/800webp/266241.webp",
  },
  {
    id: 8,
    titulo: "The Matrix",
    generos: "Action, Sci-Fi",
    anio: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    likes: 2200,
    portada: "https://static.posters.cz/image/750webp/104636.webp",
  },
  {
    id: 9,
    titulo: "Interstellar",
    generos: "Adventure, Drama, Sci-Fi",
    anio: 2014,
    director: "Christopher Nolan",
    likes: 2500,
    portada: "https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_SY679_.jpg",
  },
  {
    id: 10,
    titulo: "Gladiator",
    generos: "Action, Adventure, Drama",
    anio: 2000,
    director: "Ridley Scott",
    likes: 1800,
    portada: "https://storage.googleapis.com/pod_public/800webp/266246.webp",
  },
  {
    id: 11,
    titulo: "Titanic",
    generos: "Drama ,Romance",
    anio: 1997,
    director: "James Cameron",
    likes: 2300,
    portada:
      "https://www.originalfilmart.com/cdn/shop/products/titanic_1997_original_film_art_713cc08c-5fe2-49d1-bd32-51a1d5890d43_5000x.jpg?v=1675533926",
  },
  {
    id: 12,
    titulo: "The Lord of the Rings: The Fellowship of the Ring",
    generos: "Adventure ,Drama, Fantasy",
    anio: 2001,
    director: "Peter Jackson",
    likes: 2600,
    portada: "https://storage.googleapis.com/pod_public/800webp/251716.webp",
  },
  {
    id: 13,
    titulo: "The Silence of the Lambs",
    generos: "Crime, Drama ,Thriller",
    anio: 1991,
    director: "Jonathan Demme",
    likes: 1700,
    portada: "https://storage.googleapis.com/pod_public/800webp/180539.webp",
  },
  {
    id: 14,
    titulo: "Saving Private Ryan",
    generos: "Drama, War",
    anio: 1998,
    director: "Steven Spielberg",
    likes: 2100,
    portada: "https://storage.googleapis.com/pod_public/800webp/262764.webp",
  },
  {
    id: 15,
    titulo: "The Green Mile",
    generos: "Crime, Drama, Fantasy",
    anio: 1999,
    director: "Frank Darabont",
    likes: 1800,
    portada: "https://storage.googleapis.com/pod_public/800webp/262793.webp",
  },
  {
    id: 16,
    titulo: "Whiplash",
    generos: "Drama ,Music",
    anio: 2014,
    director: "Damien Chazelle",
    likes: 1700,
    portada: "https://storage.googleapis.com/pod_public/800webp/263562.webp",
  },
  {
    id: 17,
    titulo: "The Departed",
    generos: "Crime, Drama, Thriller",
    anio: 2006,
    director: "Martin Scorsese",
    likes: 1600,
    portada: "https://storage.googleapis.com/pod_public/800webp/263649.webp",
  },
  {
    id: 18,
    titulo: "Joker",
    generos: "Crime, Drama, Thriller",
    anio: 2019,
    director: "Todd Phillips",
    likes: 2300,
    portada: "https://storage.googleapis.com/pod_public/800webp/263142.webp",
  },
  {
    id: 19,
    titulo: "Parasite",
    generos: "Comedy, Drama, Thriller",
    anio: 2019,
    director: "Bong Joon-ho",
    likes: 2100,
    portada: "https://pics.filmaffinity.com/gisaengchung-432616131-large.jpg",
  },
  {
    id: 20,
    titulo: "The Prestige",
    generos: "Drama, Mystery, Sci-Fi",
    anio: 2006,
    director: "Christopher Nolan",
    likes: 1900,
    portada: "https://pics.filmaffinity.com/the_prestige-464630296-large.jpg",
  },
  {
    id: 21,
    titulo: "The Social Network",
    generos: "Biography ,Drama",
    anio: 2010,
    director: "David Fincher",
    likes: 1600,
    portada:
      "https://pics.filmaffinity.com/the_social_network-807781883-large.jpg",
  },
  {
    id: 22,
    titulo: "Avengers: Endgame",
    generos: "Action, Adventure, Drama",
    anio: 2019,
    director: "Anthony Russo, Joe Russo",
    likes: 3000,
    portada:
      "https://hips.hearstapps.com/hmg-prod/images/poster-vengadores-endgame-1552567490.jpg?crop=1xw:1xh;center,top&resize=980:*",
  },
  {
    id: 23,
    titulo: "La La Land",
    generos: "Comedy, Drama, Music",
    anio: 2016,
    director: "Damien Chazelle",
    likes: 1800,
    portada:
      "https://s0.smartresize.com/wallpaper/197/664/HD-wallpaper-la-la-land-jazz-gosling-stone-movie-dance-la-california-lala-jazz.jpg",
  },
  {
    id: 24,
    titulo: "Django Unchained",
    generos: "Drama, Western",
    anio: 2012,
    director: "Quentin Tarantino",
    likes: 2000,
    portada:
      "https://pics.filmaffinity.com/django_unchained-956246347-large.jpg",
  },
  {
    id: 25,
    titulo: "Coco",
    generos: "Animation, Adventure, Family",
    anio: 2017,
    director: "Lee Unkrich",
    likes: 1900,
    portada:
      "https://http2.mlstatic.com/D_NQ_NP_2X_831919-MLA29003267392_122018-F.webp",
  },
  {
    id: 26,
    titulo: "WALL·E",
    generos: "Animation, Adventure, Family",
    anio: 2008,
    director: "Andrew Stanton",
    likes: 1800,
    portada:
      "https://www.originalfilmart.com/cdn/shop/products/wall_e_2008_advance_original_film_art_4c5b9b6b-88de-4342-9cef-877261128c0f_5000x.jpg?v=1580321142",
  },
  {
    id: 27,
    titulo: "The Lion King",
    generos: "Animation, Adventure, Drama",
    anio: 1994,
    director: "Roger Allers, Rob Minkoff",
    likes: 2500,
    portada: "https://m.media-amazon.com/images/I/71tvsmgNjeL._AC_SY879_.jpg",
  },
  {
    id: 28,
    titulo: "Toy Story",
    generos: "Animation, Adventure, Comedy",
    anio: 1995,
    director: "John Lasseter",
    likes: 2000,
    portada: "https://pics.filmaffinity.com/toy_story-626273371-large.jpg",
  },
  {
    id: 29,
    titulo: "Shrek",
    generos: "Animation, Adventure, Comedy",
    anio: 2001,
    director: "Andrew Adamson, Vicky Jenson",
    likes: 2100,
    portada:
      "https://www.originalfilmart.com/cdn/shop/products/shrek_2001_original_film_art_5000x.webp?v=1678987156",
  },
  {
    id: 30,
    titulo: "Spider-Man: Into the Spider-Verse",
    generos: "Animation, Action, Adventure",
    anio: 2018,
    director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    likes: 2200,
    portada:
      "https://i.pinimg.com/736x/7a/dc/4f/7adc4fb12c2b64ea4066d04e3d0769cc.jpg",
  },
];
export default peliculas;
